<script type="text/javascript">
    $(document).ready(function($){
        
    });
</script>
<div class="header-content">
    <h2 class="left">Cadastro de Provedor SCM</h2>
</div>
<hr class="mrg-top_10"/>

<div class="mrg-top_20">
    <div id="dashboard-wrap">
        <div class="metabox"></div>
        <div class="clear"></div>
        <div class="box-content">
            <div class="box">
                <div class="radius">
                    <div class="inside">
                        <fieldset>
                            <legend>Formulário de Provedor SCM</legend>
                            <form name="form-provedor-scm" action="<?php echo $this->url(array("controller" => "cadastro", "action" => "provedorscm")); ?>" method="post" id="form" enctype="multipart/form-data">
                                <input type="hidden" name="perfil" value="2" />
                                <ul class="list-cadastro">
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label>Razão Social:</label></p>
                                                <input class="width_555" name="razao" id="razao" 
                                                       type="text" maxlength="150" value=""
                                                       onblur="javascript: this.value = this.value.toUpperCase();"
                                                       class="required"/>
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <span class="left mrg-right_47">
                                            <p><label>CNPJ:</label></p>
                                            <input class="width_130" name="cnpj" id="cnpj" alt="cnpj"
                                                   type="text" maxlength="14" value="" />
                                        </span>
                                    </li>
                                    <li>
                                        <span class="left mrg-right_47">
                                            <p><label>Inscrição estadual:</label></p>
                                            <input class="width_130" name="ie" id="ie"
                                                   type="text" maxlength="40" value="" />
                                        </span>
                                    </li>
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label>Inscrição municipal:</label></p>
                                                <input class="width_130" name="im" id="im"
                                                       type="text" maxlength="45" value="" />
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label>Nome fantasia:</label></p>
                                                <input class="width_345" name="nome_fantasia" id="nome_fantasia"
                                                       type="text" maxlength="45" value="" 
                                                       onblur="javascript: this.value = this.value.toUpperCase();"/>
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label>Atividade principal:</label></p>
                                                <input class="width_345" name="atividade_principal" id="atividade_principal"
                                                       type="text" value="" 
                                                       onblur="javascript: this.value = this.value.toUpperCase();"/>
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <span class="left mrg-right_47">
                                            <p><label>Telefone:</label></p>
                                            <input class="width_130" name="telefone_com_1" id="telefone_com_1"
                                                   type="text" maxlength="14" value="" />
                                        </span>
                                    </li>
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label>Telefone:</label></p>
                                                <input class="width_130" name="telefone_com_2" id="telefone_com_2"
                                                       type="text" maxlength="14" value="" />
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <span class="left mrg-right_47">
                                            <p><label>Site:</label></p>
                                            <input class="width_282" name="site" id="site"
                                                   type="text" value="" />
                                        </span>
                                    </li>
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label>E-mail: </label></p>
                                                <input type="text"  name="email" id="email" value="" class="width_220" />
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label>Logomarca: </label></p>
                                                <input type="file" name="logo" />
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label>Observações:</label></p>
                                                <textarea name="observacoes" id="observacoes" 
                                                          cols="65" onblur="javascript: this.value = this.value.toUpperCase();"></textarea>
                                            </span>
                                        </div>
                                    </li>
                                    <hr />
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label>Login: </label></p>
                                                <input type="text" name="login" id="login" value="" class="width_345" />
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <span class="left mrg-right_47">
                                            <p><label>Senha: </label></p>
                                            <input type="password" name="senha" id="senha" value="" class="width_130" />
                                        </span>
                                    </li>
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label>Confirmação da Senha: </label></p>
                                                <input type="password" name="senha2" id="senha2" value="" class="width_130" />
                                            </span>
                                        </div>
                                    </li>
                                    <hr />
                                    <li>
                                        <div>
                                            <span class='left mrg-right_47'>
                                                <p><label>Tipo:</label></p>
                                                <select name='tipo' id='tipo'>
                                                        <option value='0'>Selecione ...</option>
                                                    <option value='C'>Cobrança</option>
                                                    <option value='I'>Instalação</option>
                                                    <option value='c'>Comercial</option>
                                                </select>
                                        </div>
                                        </span>
                                    </li>
                                    <li>
                                        <div class='inline-block'>
                                            <span class='left mrg-right_47'>
                                                <p><label>Logradouro:</label></p>
                                                <input type='text' name='logradouro' class='width_485'
                                                       value=''
                                                       onblur='javascript: this.value = this.value.toUpperCase();' />
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <span class='left mrg-right_47'>
                                            <p><label>Número:</label></p>
                                            <input type='text' name='numero' class='width_80'
                                                   value=''
                                                   onblur='javascript: this.value = this.value.toUpperCase();' />
                                        </span>
                                    </li>
                                    <li>
                                        <div class='inline-block'>
                                            <span class='left mrg-right_47'>
                                                <p><label>Complemento:</label></p>
                                                <input type='text' name='complemento' class='width_420' 
                                                       value=''
                                                       onblur='javascript: this.value = this.value.toUpperCase();' />
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <span class='left mrg-right_47'>
                                            <p><label>Bairro:</label></p>
                                            <input type='text' name='bairro' class='width_220' 
                                                   value=''
                                                   onblur='javascript: this.value = this.value.toUpperCase();' />
                                        </span>
                                    </li>
                                    <li>
                                        <span class='left mrg-right_47'>
                                            <p><label>Cidade:</label></p>
                                            <input type='text' name='cidade' class='width_220' 
                                                   value=''
                                                   onblur='javascript: this.value = this.value.toUpperCase();' />
                                        </span>
                                    </li>
                                    <li>
                                        <div class='inline-block'>
                                            <span class='left mrg-right_47'>
                                                <p><label>Estado:</label></p>
                                                <select name='estado' id='estado'>
                                                    <option value='0'>Selecione ...</option>
                                                    <option value='ac'>Acre</option>
                                                    <option value='al'>Alagoas</option>
                                                    <option value='ap'>Amapá</option>
                                                    <option value='am'>Amazonas</option>
                                                    <option value='ba'>Bahia</option>
                                                    <option value='ce'>Ceará</option>
                                                    <option value='df'>Distrito Federal</option>
                                                    <option value='es'>Espirito Santo</option>
                                                    <option value='go'>Goiás</option>
                                                    <option value='ma'>Maranhão</option>
                                                    <option value='ms'>Mato Grosso do Sul</option>
                                                    <option value='mt'>Mato Grosso</option>
                                                    <option value='mg'>Minas Gerais</option>
                                                    <option value='pa'>Pará</option>
                                                    <option value='pb'>Paraíba</option>
                                                    <option value='pr'>Paraná</option>
                                                    <option value='pe'>Pernambuco</option>
                                                    <option value='pi'>Piauí</option>
                                                    <option value='rj'>Rio de Janeiro</option>
                                                    <option value='rn'>Rio Grande do Norte</option>
                                                    <option value='rs'>Rio Grande do Sul</option>
                                                    <option value='ro'>Rondônia</option>
                                                    <option value='rr'>Roraima</option>
                                                    <option value='sc'>Santa Catarina</option>
                                                    <option value='sp'>São Paulo</option>
                                                    <option value='se'>Sergipe</option>
                                                    <option value='to'>Tocantins</option>
                                                </select>
                                        </div>
                                        </span>
                                    </li>
                                    <li>
                                        <span class='left mrg-right_47'>
                                            <p><label>CEP:</label></p>
                                            <input class='width_80' name='cep' id='cep'
                                                   type='text' value='' />
                                        </span>
                                    </li>
                                    <li>
                                        <div class='inline-block'>
                                            <span class='left mrg-right_47'>
                                                <p><label>Caixa postal:</label></p>
                                                <input class='width_420' name='caixa_postal' id='caixa_postal'
                                                       type='text' value='' />
                                            </span>
                                        </div>
                                    </li>
                                    <hr />
                                    <li class="mrg-top_10">
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label>Banco: </label></p>
                                                <select name="codigo_banco" id="codigo_banco">
                                                    <option value="0">Selecione...</option>
                                                    <option value="santander">Santander</option>
                                                </select>
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <span class="left mrg-right_47">
                                            <p><label>Agencia:</label></p>
                                            <input class="width_80" name="agencia" id="agencia"
                                                   type="text" value="" />
                                        </span>
                                    </li>
                                    <li>
                                        <span class="left mrg-right_47">
                                            <p><label>Conta:</label></p>
                                            <input class="width_80" name="conta" id="conta"
                                                   type="text" value="" />
                                        </span>
                                    </li>
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label>Operação:</label></p>
                                                <input class="width_50" name="op" id="op"
                                                       type="text" value="" />
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label>Nome do Titular:</label></p>
                                                <input class="width_345" name="nome_titular" id="nome_titular"
                                                       type="text" value="" onblur="javascript: this.value = this.value.toUpperCase();"/>
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label>Cpf ou Cnpj do titular:</label></p>
                                                <input class="width_130" name="cpf_cnpj_titular" id="cpf_cnpj_titular"
                                                       type="text" value="" />
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="mrg-top_20">
                                            <input type="submit" class="button" value=" Cadastrar " />
                                        </div>
                                    </li>
                                </ul>
                            </form>

                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>