<?php
$perfis = $this->perfis;
?>
<script type="text/javascript">
    $(document).ready(function($){
        $('#nome').focus();
        
        $("#pf").hide();
        $("#pj").hide();
        
        $('#form').validate( {
            rules: {
                nome: {
                    required: true
                },
                login: {
                    required: true,
                    minlength: 3,
                    maxlength: 20
                },
                senha: {
                    required: true,
                    minlength: 4,
                    maxlength: 20
                },
                confirma_senha: {
                    required: true,
                    minlength: 4,
                    maxlength: 20,
                    equalTo: '#senha'
                }
            },
            messages: {
                nome: { required: 'Digite o nome' },
                login: {
                    required: 'Digite o login',
                    minlength: 'O login não pode conter menos do que 3 caracteres',
                    maxlength: 'O login não pode conter menos do que 20 caracteres'
                },
                senha: {
                    required: 'Digite a senha',
                    minlength: 'O senha não pode conter menos do que 4 caracteres',
                    maxlength: 'O senha não pode conter menos do que 20 caracteres'
                },
                confirma_senha: {
                    required: 'Digite a confirmação da senha',
                    minlength: 'O confirmação da senha não pode conter menos do que 4 caracteres',
                    maxlength: 'O confirmação da senha não pode conter menos do que 20 caracteres',
                    equalTo: 'A confirmação de senha deve ser igual a senha'
                }
            }
        });
        
        $(".tipoPessoa").click(function(){
            var valor = $(this).val();
            if (valor == "PF") {
                $("#pf").show();
                $("#pj").hide();
            } else {
                $("#pf").hide();
                $("#pj").show();
            }
        });
    });
</script>
<div class="header-content">
    <h2 class="left">Usuário</h2>
</div>
<hr class="mrg-top_10"/>

<div class="mrg-top_20">
    <div id="dashboard-wrap">
        <div class="metabox"></div>
        <div class="clear"></div>
        <div class="box-content">
            <div class="box">
                <div class="radius">
                    <div class="inside">
                        <fieldset>
                            <legend>Formulário de Usuário</legend>
                            
                            <form action="" method="post" id="form">
                                <ul class="list-cadastro">
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label for="nome">Nome:</label></p>
                                                <input class="width_345" name="nome" id="nome" 
                                                        type="text" maxlength="250" value="" />
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label for="tipoPessoa">Tipo de Pessoa:</label></p>
                                                <div class="inline-block">
                                                    <div class="inline-block" style="height: 12px;">
                                                        <input type="radio" name="tipoPessoa" value="PF" class="tipoPessoa" />
                                                    </div>
                                                    <div class="inline-block">Pessoa Física</div>
                                                </div>
                                                <div class="inline-block">
                                                    <div class="inline-block" style="height: 12px;">
                                                        <input type="radio" name="tipoPessoa" value="PJ" class="tipoPessoa" />
                                                    </div>
                                                    <div class="inline-block">Pessoa Jurídica</div>
                                                </div>
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="inline-block" id="pf">
                                            <span class="left mrg-right_47">
                                                <p><label for="cpf_cnpj">CPF:</label></p>
                                                <input type="text" name="cpf" alt="cpf" class="width_220" />
                                            </span>
                                        </div>
                                        <div class="inline-block" id="pj">
                                            <span class="left mrg-right_47">
                                                <p><label for="cpf_cnpj">CNPJ:</label></p>
                                                <input type="text" name="cnpj" alt="cnpj" class="width_220" />
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label for="login">Login:</label></p>
                                                <input class="width_220" name="login" id="login" 
                                                        type="text" maxlength="20" value="" />
                                            </span>
                                            <span class="left mrg-right_47">
                                                <p><label for="senha">Senha:</label></p>
                                                <input class="width_220" name="senha" id="senha" 
                                                       type="password" maxlength="20" value="" />
                                            </span>
                                            <span class="left mrg-right_47">
                                                <p><label for="csenha">Confirmação da senha:</label></p>
                                                <input class="width_220" name="confirma_senha" id="confirma_senha" 
                                                        type="password" maxlength="20" value="" />
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="inline-block">
                                            <span class="left mrg-right_47">
                                                <p><label for="aplicacao">Perfil:</label></p>
                                                <select name="perfil">
                                                    <option value="">Selecione...</option>
                                                    <?php
                                                    foreach ($perfis as $perfil) {
                                                    ?>
                                                        <option value="<?php echo $perfil->codPerfil; ?>">
                                                            <?php echo $perfil->nomePerfil; ?>
                                                        </option>
                                                    <?php
                                                    }
                                                    ?>
                                                </select>
                                            </span>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="mrg-top_20">
                                            <input type="submit" class="button" value=" Cadastrar " />
                                        </div>
                                    </li>
                                </ul>
                            </form>
                            
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>